### PR TITLE
Remove infinite recursion due to FileSpec change.

### PR DESCRIPTION
**Pull request by JDevlieghere**
Fixes infinite recursion due to change in how FileSpec deals with
removing the last path component.

Fixes timout for TestMiniDumpNew.py

git-svn-id: https://llvm.org/svn/llvm-project/lldb/trunk@333666 91177308-0d34-0410-b5e6-96231b3b80d8
(cherry picked from commit 9f2521522ea0402e16e06038269679a7c0f6c17e)

### CODE REVIEW

**Comment by JDevlieghere** [comment]
@swift-ci please tes and merge

**Comment by JDevlieghere** [comment]
@swift-ci please test and merge

**Comment by vedantk** [comment]
@fredriss @jasonmolenda @dcci This was auto merged into stable, and appears to have broken the lldb build there:

```
/Users/vsk/src/github-swift-master/lldb/source/Plugins/Platform/MacOSX/PlatformDarwin.cpp:1848:12: error: value of type 'void' is not contextually convertible to 'bool'
    while (platform_pull_apart.RemoveLastPathComponent()) {
```

I'll check whether it reverts cleanly.

**Comment by fredriss** [comment]
It's not clear to me how this can work on 4.2 and be broken on stable. Both branches are supposed to have basically identical LLDB content. I'm sure this will conflict/break on upstream-with-swift though.

**Comment by vedantk** [comment]
This reverted cleanly on stable and started passing tests, so I pushed the revert to unblock the bots: https://github.com/apple/swift-lldb/pull/668

I'll look into the divergence between 4.2 and stable

**Comment by vedantk** [comment]
Some FileSpec changes (edit) _were reverted from_ stable, but not 4.2, hence the divergence.

**Comment by fredriss** [comment]
Is it obvious whether those FileSpec changes were put on stable on purpose?

**Comment by vedantk** [comment]
It's unclear whether this was intentionally put on stable, but I think it was:
https://github.com/apple/swift-lldb/pull/665

When we found an issue with the commit on the bots, however, the commit wasn't reverted on 4.2.
